spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/agroeti
      username: root
      password: admin
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
    generate-ddl: true
    show-sql: true
      
      
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${cognito-client-id}
            client-secret: ${cognito-client-secret}
        provider:
          cognito:
            issuer-uri: ${cognito-issuer-uri}

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin